apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
data:
  # property-like keys; each key maps to a simple value
  sqlconnectionstring: "Server=10.183.146.167;Database=jemsmmdev;Min Pool Size=5;Application Name=process-alerts_CI_DFDEV;User ID=jemsmmapp;Password=ka1RvXAIOVwcH6URg5Kk"

  # file-like keys
  appsettings.json: |
    {
      "EnvironmentValues": {
        "SQLConfig": {
          "Server": "jemsmmdb",
          "LegacyJemsServer": "azuse2gdlsql81.corp.jabil.org",
          "SSISDbServer": "azuse2sqltest81.corp.jabil.org",
          "Database": "jemsmmdev",
          "CustomDatabase": null,
          "CamxServer": null,
          "CamxDatabase": null,
          "ConnectionProperties": "Min Pool Size=5;MultiSubnetFailover=True;ApplicationIntent=ReadWrite",
          "Authentication": "User Id=jemsmmapp;Password=ka1RvXAIOVwcH6URg5Kk"
        },
        "EnvironmentName": "AWSDEV2",
        "URL": {
          "Hostname": "dev.jemsmm.corp.jabil.org",
          "DefaultSubdomain": null,
          "Protocol": "https",
          "BaseUrl": "${EnvironmentValues:URL:Protocol}://${EnvironmentValues:URL:Hostname}"
        },
        "SFM_URL": {
          "Hostname": "USPLND0SFMDEV42",
          "Protocol": "http",
          "BaseUrl": "${EnvironmentValues:SFM_URL:Protocol}://${EnvironmentValues:SFM_URL:Hostname}"
        },
        "SFMConveyorController": {
          "InstanceName": "KKW_CC02",
          "IFactoryMode": true
        },
        "ApplicationInsights": {
          "InstrumentationKey": "f5dce8ab-60f1-4413-95bf-8237ff1a4ad8"
        },
        "TokenCertificateName": "IFactory.Certs.CodeSigning.NonProduction",
        "MSMQServiceHost": null,
        "Wiki": {
          "BaseUrl": "http://usplnd0wiki01:8090",
          "SQLConfig": {
            "Server": "alfrdcmesdoc01",
            "Database": "PhoenixWiki",
            "Authentication": "User ID=JEMS;Password=JEMS123"
          }
        },
        "SSRS": {
          "BaseUrl": null,
          "Folder": null
        },
        "Okta": {
          "SigninUrl": "https://jabilappdev.oktapreview.com",
          "ClientId": "0oawacsoq2UfgSs810h7",
          "ClientSecret": "BCX8TnMoK1AN6i7IaeLv_t6G--jKCdBwerDSZmSp",
          "CallBackUrl": "/auth/authorization-code/callback",
          "SignOutCallBackUrl": "/auth/signout/callback"
        },
        "FeatureFlags": {
          "ApiKey": "abqhg6kefi2qc8iuoh1pfld43s3800bhb4cm",
          "ApiKeyBrowser": "qdqm9ds5n8p0l9gb2t7t0amijn7tqnc50pcb",
          "FeaturesRefreshRate": 60,
          "SegmentsRefreshRate": 60
        },
        "I18n": {
          "BaseUrl": "https://api-dev.i18n.jabilapps.com",
          "ApiKey": "i65D5eAsEL5UF4E8V7CWe4CscQWjkXIRa4BVPXA0",
          "ApplicationId": 8
        },
        "ExternalServices": {
          "EmailServer": {
            "HostBaseUrl": "azeuweweb80.corp.jabil.org",
            "HostPath": "email/api",
            "Port": 4092,
            "Protocol": "https"
          }
        },
        "RMAConfig": {
          "Database": "RMA_DEV"
        }
      },
      "EnvironmentOptionsBase": {
        "Hostname": "${EnvironmentValues:URL:Hostname}"
      },
      "IotFactoryGateway": {
        "BaseUrl": "http://mxgdlm4iot91.corp.jabil.org:8081",
        "Name": "ifg_usplnd0iot90"
      },
      "IotProfilerConfig": {
        "SiteOptions": [
          {
            "SiteCode": "GDL",
            "BaseUrl": "http://mxgdlm4iot01.corp.jabil.org:8855"
          },
          {
            "SiteCode": "HUA",
            "BaseUrl": "http://cnhuam0jestgi81.corp.jabil.org:8857"
          },
          {
            "SiteCode": "MTY",
            "BaseUrl": "http://mxgdlm4iot01.corp.jabil.org:8855"
          },
          {
            "SiteCode": "UZH",
            "BaseUrl": "http://uauzhm0iot81.corp.jabil.org:8855"
          }
        ]
      },
      "MuleSoft": {
        "BaseUrl": "https://api-dev.corp.jabil.org",
        "UserName": "18ae7046f56443488037d41fde4156f7",
        "Password": "521a308d61fE4afc85AC3b1a65c7E284"
      },
      "Mii": {
        "BaseUrl": "http://azuse2sql41.corp.jabil.org:50000",
        "UserName": "DEV020FOF",
        "Password": "CbUy112!2"
      },
      "MuleSoftSetupSheetsService": {
        "BaseUrl": "https://api-dev.corp.jabil.org",
        "UserName": "5ccd13f881a544d9b77d1d4c4d8d4c0f",
        "Password": "91d36511530b4Cdea2E5fDb88cA963db"
      },
      "MulesoftPlannedOrderService": {
        "BaseUrl": "https://api-dev.corp.jabil.org",
        "PlannedOrderEndpoint": "sap/pp/plnorder/sys/v1/api/plannedorder",
        "UserName": "5ccd13f881a544d9b77d1d4c4d8d4c0f",
        "Password": "91d36511530b4Cdea2E5fDb88cA963db"
      },
      "SqlConfigBase":
      {
        "SqlConnectionString":"Server=10.183.146.167;Database=jemsmmdev;Min Pool Size=5;Application Name=process-alerts_CI_DFDEV;User ID=jemsmmapp;Password=ka1RvXAIOVwcH6URg5Kk",
        "SqlHealthCheckConnectionString":"",
        "MaxRetryCount":5,
        "TimeIntervalBetweenRetryInSeconds":50
      },
      "AuthOptionsBase": {
        "BaseUrl": "http://localhost:8020",
        "SignInUrl": "api/cookie",
        "ClaimCacheDuration": 300,
        "UseCommonSecurity": true
      }
    }