apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceexample
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: serviceexample
      app.kubernetes.io/instance: serviceexampleinstance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: serviceexample
        app.kubernetes.io/instance: serviceexampleinstance 
    spec:
      containers:
      - image: serviceexample:v7
        name: serviceexampleapi
        imagePullPolicy: Never
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /app/kubernetesAppSettings.json
      #     subPath: kubernetesAppSettings.json
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: config-test